env : "dev"
storage : "./storage"
http_server: 
  addres : "localhost"
  port: "8888"
  timeout: 4s
  idle-timeout: 60s
pages :
  equals_page : "../front/equals.html"
  molar_page : "../front/molar.html"
  balance_page : "../front/balance.html"